CentOS-PaaS-SIG/ci-pipeline

- config/Dockerfiles/rpmbuild/Dockerfile
- tasks/rpmbuild-test
This PR mounts a directory from the duffy host inside of the fedora container that does the fedpkg mockbuild. 
It also adds config options to use that space as the directory for the mockbuild so that it does not run out of disk space when building the kernel package.
> Let mock chroot use space from duffy host in rpmbuild

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
The build description is set to change based on the make test return code, but since groovy isn't in the environment yet, there is nothing to show.  Also, probably best to have this as its own file anyway.
> Copy make test output to a file

- jobs/ostree-compose.yml
This PR changes the ostree publisher which triggers the image compose job to be a builder.  The reason this is necessary is that as is, the publisher is running twice for some reason.  It seems flexible publish has some conflict with other postbuild actions.  So, changing to a builder seems to fix this.  Functionally, it should make no difference, as it will be the last build step.  There is no threshold value in the builder, but that should be fine because if the previous build steps failed, I believe that no later build steps will execute - e.g. if the build step failed, this builder won't execute anyways.  This change seems to work.  Pretty sure the jjb is correct as well...
> Fix ostree trigger of image compose job

- tasks/rpmbuild-test
I don't even remember why I had injected a c into the RSYNC branch variable... I think it was from I used that variable for libabigail as well.
> Use fed_branch for rsync dir name

- jobs/rpmbuild.yml
This should fix the failure.  This may have changed from 1.6.1 to 2.0.0
I recommend until we have a gate job or pipeline gate job we run through with 2.0.0 version we have in production which is this sha 7e1e54633f835d1c6ecd989452c9125c1ea9a921
> Fix to be an a list of projects not a string

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
Write rpmlint on directory of rpms to file to be archived in logs file.
Also made the make test part a little cleaner.
> add rpmlint to rpmbuild job

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
Currently printing out the entire path to the rpm, I just want the full rpm file name without the path to it here.
> Fix logic to echo rpm name to a file

- tasks/kernel-kt0
F25 has python3, not python, so had to fix that in the inventory file.
Also add -v to call to libvirt playbook as no tasks are failing, but the return code is 2 right now
> fix up some python3 vs python2 compatibility issues, add verbosity

- jobs/kernel_trigger.yml
- tasks/kernel-kt0
Add commented out code to kernel trigger job so that once the rpmbuild job can publish fedmsg with the proper topic, the kernel trigger job can use that to trigger instead of hackish shell steps.  Also add set -x to kernel job for better output.
> Prepare kernel job for fedmsg triggering

- jobs/kernel_trigger.yml
The kt0 job has a kernel_nvr parameter, not packagename
> Align parameter names for kernel jobs

- jobs/kernel-f25-kt0.yml
- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
- tasks/kernel-kt0
This enables a playbook to run the LTP testing suite if the kernel installed successfully.  It copies the logs to the proper directory so that they should be archived properly.  Once this is running and confirmed to be working as expected, I will add another PR to put fedmsgs around this.
> Turn on LTP testing for f25 kernel job

- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
I am getting null pointer exceptions in the CI notifier when I have   "test_guidance": "${test_guidance}" when test_guidance='' so just remove it and use "" as the value instead.
> Remove test guidance from rpmbuild messages

- jobs/atomic-host-tests.yml
- jobs/ostree-compose.yml
- tasks/atomic-hosts-tests
- utils/ansible_xunit.sh
This adds the atomic-host-tests after the ostree-boot-verify job succeeds.  There are ~10 playbooks in atomic-host-tests, some have worked for me some haven't; I turned most of them on so that I can see what I am working with in the exact environment it will be running in.  I can turn some off after analyzing outputs.  I will add the fedmsg stuff in another PR once this workflow is solidified.
> Add atomic-host-tests workflow

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
Bill made a good point that if the build step fails, subsequent build steps will not happen so we will not publish.  So, change the jms stuff to publisher where it makes sense.  This is very much dependent on inject still running if the build step fails before it.
> make some jms stuff publisher in case build step fails

- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
In jobs/rpmbuild.yml, the fedmsg fields are used in both a builder and publisher, so we write them to a file.   job.properties was replaced by package_props.txt, so I got rid of _running since it is the only job.properties now.  Also fix the cat << EOF >> so the fields aren't all messed up and give null pointer exceptions.
In jobs/rpmbuild_trigger.yml, we only have one instance of jms_messaging so it makes no sense to cat the fields to a file, just put them right in the publisher.
> Clean up rpmbuild fedmsgs

- utils/ostree_install_rpms.yml
The kubernetes testing fails right now anyways, and I am getting errors installing the kubernetes rpm, so just turn this off for now so that we can get at least some of the testing going.
> Turn off kubernetes rpm install for now

- tasks/atomic-host-tests
The console logs show this test running for 9+ hours before a broken pipe occurs with the duffy host, so I get no logs.  This did not happen when I ran it on a local VM.  Turning it off for now and will debug and figure it out before turning it back on.
> Turn off improved-sanity-test for now

- jobs/ostree-compose.yml
- tasks/ostree-image-compose
One for ostree/repo and one for ostree/image.
move image creation back to a builder step.  We really don't want to trigger if the ostree repo creation failed.
commit from ostree repo creation should get passed all the way to boot sanity testing.
Create a latest-atomic.qcow2 symlink.
> Split boot sanity into two jenkins jobs.

- jobs/atomic-host-tests.yml
- jobs/ostree-compose.yml
Leaving the .complete message in atomic-host-tests as TODO for now so I can devise a smart solution for that tomorrow
> Add fedmsgs to atomic-host-tests

- tasks/kernel-kt0
Currently, something in the ltp testing suite kills the ssh connection, so despite the task for synchronizing the logs being in an always: block, it does not run as the ssh connection is killed.  However, it appears the logs are there once the playbook finishes regardless, so manually scp them as a hackish solution for now.  Also adding in that dmesg command, as it is another task in the playbook that isn't running.
> Attempt at fixing ltp run

- tasks/ostree-image-compose
previous image.  Probably should just read the symlink but this was
quicker.
> Now that we have a latest-* symlink fix the logic to find the correct

- config/libvirt-setup/roles/libvirt-system/tasks/main.yml
these are ansible variables and don't need to be referenced via jinja2.
> Clean up noise in log files.

- jobs/atomic-host-tests.yml
- jobs/ci-pipeline-defaults.yml
- jobs/kernel-f25-kt0.yml
- jobs/ostree-compose.yml
- jobs/rpmbuild.yml
The kernel ltp testing is getting ssh killed after ~6hours.  It needs longer to run.  This is the only timeout variable I could find in our provisioning so hopefully this fixes it.
> Change duffy timeout to a variable and set it higher in kernel job

- library/beakerlib.py
So far, this ansible module seems to work for rlRun, rlAssertGrep, and rlAssertNotGrep from the command line execution of it as described in the 'Examples' section.  Some things to think about are what other beakerlib functions we want to add, the output we give, and whether or not we want to support running rlRun commands the shell way instead of the command way, as I believe this only does it the command way since I took from that module's code.  Regarding output, an example is I do not currently give as output the command you ran with rlRun, nor the file or string parameters you input.  Not sure how necessary that would be.  We also would likely eventually need some checks to make sure arguments are provided when they are required.
> Initial commit of beakerlib ansible module

- tasks/atomic-host-tests
The sshpass stuff allows docker-build-httpd to work and rpm-ostree is a new test that now exists in the repo
> Add more tests

- jobs/rpmbuild.yml
Concurrency helps keep the queue down, but even with 20 executors I'd rather not have ~15 rpmbuilds going at once.
> Throttle concurrent rpmbuilds

- tasks/atomic-host-tests
07:05:56 + ara generate junit -
07:05:56 ./ci-pipeline/tasks/atomic-host-tests: line 38: /logs/ansible_xunit.xml: No such file or directory
Didn't dive in too deep, but I think this is the fix
> Update atomic-host-tests ara generation

- tasks/rpmbuild-test
I think we should disable all the rsync locking stuff for now as we test out the ci-pipeline, as aborting a build messes up the locks [1].  We can turn them back on after, I don't see us running into problems with this turned off for now.
[1] Say a jenkins build starts a bash task on a duffy host.  If you abort the jenkins build, the duffy process is killed.  This allows the duffy host to be cleaned up as expected, but the duffy host's processes don't exit cleanly... so the bash task running on the duffy host doesn't get to run its traps.  So if you abort a build that pushed an rsync lock and hadn't yet deleted it, that lock is staying there and all future builds will hang until we go in and manually delete the lock.
> Temporarily disable rsync locking

- config/Dockerfiles/rpmbuild/Dockerfile
Granted it is not the best solution, this seems to allow the rpmbuild container to advance past the error it has been getting since 3am July 4th.
> Update Dockerfile for rpmbuild to f24

- config/Dockerfiles/package_tests/image/Dockerfile
- config/Dockerfiles/package_tests/image/image_package_test.sh
Provided an image, like the various qcow2 images the pipeline produces, this container will run all currently published package level testing on said image.  There is no need for a separate provisioner or anything, it is all taken care of in the container.  The one caveat is that the host the container runs from must have the kernel kvm modules.
Still a work in progress creating a second container which takes an ansible inventory as input instead of an image to run testing.  Getting hung up on the ansible local connection stuff from inside the container; it will come as a separate PR.
> Add dockerfile to run package level tests against an image

- config/Dockerfiles/package_tests/ansible/Dockerfile
- config/Dockerfiles/package_tests/ansible/ansible_package_test.sh
- config/Dockerfiles/package_tests/image/image_package_test.sh
- tasks/rpmbuild-test
This container takes in an inventory file and a private key as inputs and runs package level testing against the ansible host.  It is set up to require both the ssh private key and the inventory file to be in the same directory on the host it is called from.  It also writes the artifacts out to that same directory.
Also fixes a small check in the rpmbuild task for deciding whether or not to build the image that Bill pointed out.
> Add docker container to run package level testing against an ansible host

- config/Dockerfiles/rsync/rsync.sh
> Allow rsync_opts to be passed to the rsync container, but default to --delete

- tasks/rpmbuild-test
Granted it is a lot of docker runs, this is a more containerized way to run the rpmbuild task.  Mostly I just containerized the rsync steps.  The locking is still commented out.
> Make the rpmbuild task more containerized

- jobs/rpmbuild_trigger.yml
Until the old pipeline is 100% deprecated, we need the trigger to allow concurrency in case of rebuilds where 2000+ changes come rapidly, similar to this morning.
> Make rpmbuild trigger concurrent

- tasks/rpmbuild-test
Pipeline is in a good state now, let's turn rsync locks back on for the rpmbuild stuff
> Turn on rpmbuild rsync locks

- config/Dockerfiles/package_tests/ansible/ansible_package_test.sh
- config/Dockerfiles/package_tests/image/image_package_test.sh
Some packages have a test_local.yml file already provided, which is nice because it tells you the tests that exist.  The reason why that is nice is because some tests aren't named runtest.sh, so I would currently miss those.  So, this modification uses test_local.yml if it exists, instead of just making our own every time.
> Take advantage of test_local.yml files if they are provided

- Jenkinsfile
- We need to verify we can talk to a duffy host
and that requires an ssh key since we are no longer
on the fedora-atomic slave
> Add the fedora-atomic key via jenkins credentials

- Jenkinsfile
- ostree-boot-sanity and atomic-host-tests
should use system-setup.yml instead of rdgo-system.yml
> Change to use system-setup.yml playbooks

- Jenkinsfile
Also fix rsyncResults to call the tasks consistently and without a
double ././
> Don't escape the variables.  We need the current values.

- config/s2i/jenkins/continuous-infra-jenkins-master-s2i-template.yaml
The default Jenkins image will add only 100m of Metaspace for the Java JVM
This is not enough since Groovy heavily uses the metaspace.
> Add JAVA_GC_ARGS to Jenkins DeploymentConfig

- Jenkinsfile
- jobs/ostree-compose.yml
- tasks/ostree-boot-image
We will want this to be its own job.  However, I think we should turn this on for now until we get there, so we can say we are running these tests in the pipeline.  In order for it to be its own job, we will have to modify the ostree-boot task to not tear down the host and to pass its inventory file and key along to the package testing task.  This would require not tearing down the duffy host as well.  But, we are moving to containers, so not sure what it means in that case.  So, since adding it cleanly is a little complicated for now, I think we should temporarily add it like this.  Once we have ostree-boot working in a container, we can worry about separating it out and defining the workflow for how the two work together.
> Add package level testing to ostree-boot task for now

- config/Dockerfiles/ostree_compose/ostree-compose.sh
- touch /home/output/logs/ostree.props
- ex. of failure https://jenkins-continuous-infra.apps.ci.centos.org/job/ci-pipeline-f26/139/console
> Issue since ostree.props doesn't exist in certain runs

- Jenkinsfile
Per my conversation with Ari, creating a PR so that Upstream CI doesn't hit this issue if some future field in a message they receive also has a dash the way the message downstream CI gets does. (this is to address how we get 'message-content' and have to change it to 'message_content' to make it serializable.
> Handle dashes in FedMsg fields

- tasks/ostree-compose
from the previous run.  So just delete the logs and it must be
done via sudo because the containers run privileged.
> removing the output dir was really just to clear the logs

- config/Dockerfiles/ostree_image_compose/ostree-image-compose.sh
- tasks/ostree-boot-image
Only update the symlink when the boot sanity job passes.
also make sure we don't garbage collect what the latest symlink is pointing to.
> Move latest symlink logic

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- tasks/rpmbuild-test
These changes to the rpmbuild container are meant to make the migration into OpenShift easier.  I put the rsync aspects of the rpmbuild flow into the container so it is all one container call.  It will still exit before going near any rsync stuff if make test fails or any of the rpmbuild stuff fails.  No changes should be needed in the Jenkinsfile, as no additional arguments are needed and it is still just a call to the duffy builder with the same task.  I made all the changes in the task file and container config so it should *just work.*  
Once approved, I will merge it when I am going to be online for a bit so I can monitor it to make sure I didn't break anything.
> Improve rpmbuild container and have it do the rsync as well

- Jenkinsfile
- This caused a recent failure
https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/36/console
- We should just throw out anything that doesn't start with
^fed since we don't need this issue
> More substitution needed in fedmsg_fields.txt

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- tasks/rpmbuild-test
All this stuff was previously approved and merged, I just had forgotten a / in the pathing for the rsync stuff so it wasn't working.  When I saw it wasn't working, I reverted the previously merged PR.  That is why this has all the changes again, not just the pathing fix.
> Update rpmbuild container with proper pathing

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
The path to the directory to the rpm is currently wrong so the nvr field isn't resolved properly.  This is one of the fixes I had made in the larger fix PR but stripping it out to get it fixed immediately.  Tested this, this is the fix.
> Small path issue to fix nvr resolution

- Jenkinsfile
- Jenkinsfile-sl-pipeline
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/cicdPipeline.groovy
- vars/rpmBuild.groovy
Updated the writeFile call with a python script that does the following:
* Parses the CI_MESSAGE env variable into JSON
* If the CI_MESSAGE contains a 'commit' key, it performs the following
* For any key, if the key value is a string, replaces any double quote
character within the value with a single quote.
* Truncates the value of the message key at the first newline character
* Writes the key/values in the following format to a file named
fedmsg_fields.groovy in the workspace.
* env.fed_{key}="{value}"
This removes the need to convert any files and this fedmsg_fields.groovy
file is injected with a call to load the file object.
> UPDATE python file to parse and write groovy props

- Jenkinsfile
- vars/rpmBuild.groovy
Fixed the python script to parse the CI Message due to differences
between python3 (my dev env) and python2 (production env). Additionally,
adding a script, but failing to execute it in the pipeline does no good.
As such, I added sh steps to chmod+x the script and actually run it.
Finally, per @alivigni I uncommented the final sendMessage call in the
Jenkinsfile
> FIXED python script to parse CI_MESSAGE

- config/Dockerfiles/rpmbuild/Dockerfile
We are mounting /home, so we can't have the build script be in /home
> Update Dockerfile for rpmbuild

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
When I copied the new logic for adding the rpm and original_spec_nvr fields from the old container into the new, I forgot to change the package properties file path.
> Fix log location for new rpm name fields

- config/Dockerfiles/rpmbuild/Dockerfile
Add this package to the rpmbuild container as it should provide kinit.  The kinit in rpmbuild is currently failing for no such kinit.
> Add python-krbV to rpmbuild container

- tasks/kernel-ltp
The kernel ltp job is more of a standalone thing for the kernel team to get some testing on the upstream kernel and check the results.  It isn't integrated into the pipeline (no idea when that would happen) and is still on ci.centos.org as a standalone job.  As such, it has no HTTP_BASE variable defined.
> Give the kernel job HTTP_BASE

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
Now with the credentials, we can concurrently build in koji as well.
> Turn on concurrent koji rpm building

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
We want accurate time measurements so let's not exit the command until it is finished.
> Wait for koji tasks to finish

- config/Dockerfiles/package_tests/ansible/ansible_package_test.sh
- config/Dockerfiles/package_tests/image/image_package_test.sh
Currently the package level test containers just call the playbook if there are tests there that are beakerlib.  If there are beakerlib tests there, but they are not tagged for atomic, it will run and pass but have no results because nothing run, which is kind of confusing.  With this, it will echo out that there are no atomic tagged tests and do nothing.
> Check if there are atomic tagged tests first

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
The rpmbuild container searches for the Makefile's directory.  This was dependent on said directory containing the package name in its name.  That is not always the case.  This improves on that.  Also, some fedpkg preps (vim in particular) require perl, so install that.
Manually calling make test and ./configure may not be the best idea, so will have to be revisited.
> Fix up rpmbuild Makefile find

- Jenkinsfile
The atomic-host-tests stage is provisioning duffy, exiting, then tearing down the duffy instance.  Not sure if this is why, but it is my first guess.
> Debugging atomic-host-tests stage

- Jenkinsfile
Currently, the atomic-host-tests stage just provisions a duffy host and tears it back down.  It has no rsync step, which is the part that rsyncs the proper files over to the duffy host and executes them.  As such, nothing is happening in the atomic-host-tests stage right now, but it should now.
> Add duffy step for atomic-host-tests

- playbooks/roles/rdgo-system/tasks/main.yml
newer librepo package built in atomic-testing does not
provide python-librepo which is required by bodhi-client
which is required for fedpkg now.
> exclude newer librepo from atomic-testing repo.

- Jenkinsfile
The step to consume the xunit results from the atomic-host-tests was previously commented out.  I assume this is because the atomic-host-tests stage was not configured properly, so none of the tests were running, so there were no xunit files to consume.  That has been fixed, so we can consume the results now.  The xunit file is ${env.ORIGIN_WORKSPACE}/logs/ansible_xunit.xml, which was what the path was in the commented code, but changing it to wildcards as has been done here allows more flexibility for more xunits to be added in the future and should still work as expected here.
> Turn on atomic-host-tests XUnit step

- utils/atomic_rollback.yml
The atomic-host-tests stage is set up to rollback the host after each test.  If the test doesn't mess with the host too bad or add a deployment, and you tell it to rollback, it will fail, which is going to taint the ara generated xunit reports.  Now, it will only rollback if it has something to rollback to, so it should not fail.
> only rollback if you have something to rollback to

- Jenkinsfile
20:11:56 [xUnit] [INFO] - Processing JUnit
20:11:56 [xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern '/tmp/workspace/continuous-infra-ci-pipeline-f26/ci-pipeline-atomic-host-tests/logs/ansible_xunit.xml' relative to '/tmp/workspace/continuous-infra-ci-pipeline-f26' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
20:11:56 [xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern '/tmp/workspace/continuous-infra-ci-pipeline-f26/ci-pipeline-atomic-host-tests/logs/ansible_xunit.xml'. Configuration error?.
20:11:56 [xUnit] [INFO] - Failing BUILD.
20:11:56 [xUnit] [INFO] - There are errors when processing test results.
20:11:56 [xUnit] …
> Comment atomic host tests xunit back out

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
[root@hp-z420-01 container-selinux]# cat container-selinux.spec | grep '%{?dist}'
Release: 1%{?dist}
[root@hp-z420-01 container-selinux]# cat ../glibc/glibc.spec | grep '%{?dist}'
%define glibcrelease 15%{?dist}
[root@hp-z420-01 container-selinux]#
Not every .spec file just says Release: foo%{?dist}. Some, like glibc shown above, use other variables, but they will use %{?dist} in their definition regardless, so just replace that.
> Better modification of .spec file's release

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
For libabigail, you cannot pass master or rawhide as your distro, so I had hardcoded master to be fc27.  However, for some reason, if you pass it in a release greater than the highest that exists, it defaults to latest, so at time of writing fc99 defaults to fc28, so this should work until we get to fc100, which is good enough for me.
> Fix hardcoded f27=master in rpmbuild

- Jenkinsfile
16:33:04 Add correct host key in /home/jenkins/.ssh/known_hosts to get rid of this message.
16:33:04 Offending ECDSA key in /home/jenkins/.ssh/known_hosts:4
This should fix that error as far as I know.  Hopefully I put it in the right spot.
> Clear ~/.ssh/known_hosts every time

- Jenkinsfile
The pipeline doesn't like connecting to duffy without a known_hosts file either.  We will need to do something with the UsersKnownHostsFile or something. Not sure yet.
> Revert removal of known_hosts

- Jenkinsfile
indenting in the jenkins file is confusing to know where to put
the EOF marker.
> Use echo instead of heredoc since the indenting

- Jenkinsfile
jbieren pointed out you lose lines when you outout to a variable.
So need to do the grep inline before var assignment.  But we can't
add the sed or we will always pass unless we turn on pipefail.
> really fix this method for one last time.

- config/Dockerfiles/ostree_compose/Dockerfile
newest bodhi-client has fixed dependencies to not
require python-dnf.
> Pull bodhi-client direct from koji build

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
We were sticking to F24 for the rpmbuild container because mock wasn't working on F25. It wasn't working on F26, either.  It wasn't working on those releases because it was using nspawn.  This should fix it (worked locally for me).
> Update rpmbuild container to f26

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
I believe adding build logs for the rpm stage should be this easy. I will be curious of the stage pipeline results on this though, as I am not 100% sure if the ostree stages will complain about something besides .rpm files being in the artifact directories.
> Add rpm build logs

- Jenkinsfile
- src/org/centos/pipeline/PipelineUtils.groovy
- tasks/ostree-image-compose
This forces image-compose to run every time, but it will only rsync if the conditions from before are met.  It then copies the qcow2 into the workspace.  This sets us up to allow package testing with that as the subject if it works.
> Create an image every time

- Jenkinsfile
- src/org/centos/pipeline/PipelineUtils.groovy
- tasks/ostree-image-compose
I previously put ostree boot sanity before image compose, because I did not see why you would build an image for an ostree that doesn't even boot, but ostree boot requires an image to exist to work.
> ostree-image-compose must come first

- config/Dockerfiles/ostree_image_compose/ostree-image-compose.sh
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
Currently, if the mock build just fails, the build logs are never moved to the proper spot to be archived and stored as jenkins artifacts (still no rsync would happen in this scenario)
> Archive logs on mockbuild failure

- src/org/centos/pipeline/PipelineUtils.groovy
Updated setMessageFields() to use build a HashMap instead of a string
when creating the messageProperties. This allows for overwriting of
values instead of having to set them on a message type basis.
> UPDATE setMessageFields() to use HashMap

- Jenkinsfile
- config/Dockerfiles/package-test/Dockerfile
- config/Dockerfiles/package-test/integration-test.sh
- config/Dockerfiles/package-test/package-test.sh
Will have a followup PR later to rename the package-test container to something more general as it encompasses the integration tests as well.  Had to disable three integration tests as they reboot the host and standard-test-roles does not currently support that.
> Containerize atomic host tests

- Jenkinsfile
The integration tests in a container passed just fine in stage, but we have been getting hanging processes for the last day whenever it runs. Until we can fix that, we should disable these.
> Hotfix disable integration tests

- config/Dockerfiles/singlehost-test/package-test.sh
In the current workflow, if the commit in question changes the tests in the dist-git repo, they wouldn't be picked up as we would just be on master.
> Checkout rev before running package tests

- src/org/centos/pipeline/PipelineUtils.groovy
Currently, if a stage that is executing in a container fails, the logs are archived in Jenkins in the "logs" directory.  We would like that directory to include the stage name, even if the container call failed.  Hopefully, this accomplishes that.  If it passes initial testing, I will have to manually retrigger with a CI_MESSAGE that should fail, to ensure the fix worked.
> Copy logs to stagename/logs if container fails

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
We need mock to use the increased OpenShift filesystem so it can build the kernel. If this passes stage, I will manually trigger it to build a kernel in stage as well before merging to ensure this works.
> Change mock's fs path to use increased pod fs

- config/Dockerfiles/ostree_compose/ostree-compose.sh
Updated the ostree-compose.sh file to pull the
fedora-atomic-testing.json file from the upstream fedora source so that
we always have up to date data.
> Pull fedora-atomic-testing.json from upstream

- src/org/centos/pipeline/PipelineUtils.groovy
Updated task value for ci-pipeline-ostree-image-boot-sanity as it was
pointing to an incorrect value after the jenkinsfile refactor in August.
Mea culpa.
> UPDATE task for ci-pipeline-ostree-image-boot-sanity

- config/Dockerfiles/ostree-image-compose/Dockerfile
- config/Dockerfiles/ostree-image-compose/default.xml
We should leave virbr0 open for anything that needs it; I don't believe any of our workflow should take that bridge every time.
> Specify ostree-image-compose default libvirt bridge

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
We use ~ for the rpmbuild parent dir, not /root
> Fix lingering /root in rpmbuild container

- config/Dockerfiles/ostree_compose/ostree-compose.sh
If you look at the upstream files, they now just call include on -base, so we need to get that file too. It exists on both f26 and f27.
> Update ostree-compose.sh with fedora-atomic-host-base

- config/Dockerfiles/singlehost-test/package-test.sh
Pretty much all tests that are ported to dist-git are only being put into the master branch. Thus, the f26 and f27 pipelines will almost never run any tests.  Proposing we run the master tests for now, just so tests are being run more often.  The only real negative to this is that we are not verifying the addition to tests to the dist git repo as a change like we would like and if there is a test that runs on master, but not f26, we will be running it anyways. I don't really think that the dist git test addition is ready yet for those scenarios, so this is likely fine for now
> Run master package tests

- Jenkinsfile
- config/Dockerfiles/linchpin-libvirt/linchpin_workspace/run_e2e_tests.sh
- config/Dockerfiles/ostree-boot-image/ostree-boot-image.sh
- config/Dockerfiles/ostree-image-compose/ostree-image-compose.sh
- config/Dockerfiles/ostree_compose/ostree-compose.sh
Use the mounted dir instead of /home/output in the containers. Also, stop using dir(ci-pipeline), as that is messing with log archiving. 
@p3ck, I removed the rsync pull of images before ostree-boot-sanity, since we pull it before ostree-image-boot-sanity anyways. Do you think that is okay, or do we require the second rsync? It seems redundant to me.
> Stop using /home/output

- README.md
https://fedoraproject.org/wiki/Changes/InvokingTestsAnsible holds
deprecated information.
Current CI test specification is located at different URL:
https://fedoraproject.org/wiki/CI/Tests
Signed-off-by: Andrei Stepanov <astepano@redhat.com>
> Update README.md URL for CI tests specification.

- README.md
- No need to include Fedora infrastructure in the document
this diagram is won't be kept out of date and isn't accurate
> Remove diagram for Fedora pieces since this is out of date

- config/s2i/create-containers.sh
This was added back in by a rebase error in a previous PR.  It is all singlehost container now.
> Remove package test from create-containers.sh

- config/Dockerfiles/ostree-image-compose/Dockerfile
Since this passed stage to get in, we could probably just remove this package altogether, but
> Fix typo in image-compose Dockerfile

- config/Dockerfiles/linchpin-libvirt/Dockerfile
- config/Dockerfiles/linchpin-libvirt/paas7-openshift-origin36-testing.repo
paas7-openshift-origin36-testing.repo is added to install latest
origin-tests rpm to avoid any further failure due to updates in
origin-tests binaries.
> Added paas7-openshift-origin36-testing.repo to container

- config/Dockerfiles/fedmsg-relay/Dockerfile
- config/Dockerfiles/fedmsg-relay/endpoints.py
- config/Dockerfiles/fedmsg-relay/entrypoint.sh
- config/Dockerfiles/fedmsg-relay/relay.py
- config/Dockerfiles/fedmsg-relay/ssl.py
- config/s2i/fedmsg-relay/create-fedmsg-relay.sh
- config/s2i/fedmsg-relay/fedmsg-relay-template.yaml
- config/s2i/jenkins/continuous-infra-create-openshift-project
- config/s2i/jenkins/continuous-infra-slave-template.yaml
- config/s2i/jenkins/jenkins-master-template.yaml
- config/s2i/jenkins/master/configuration/init.groovy
- config/s2i/jenkins/master/configuration/jobs/fedmsg-devel-receiver-test/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedmsg-devel-sender-test/config.xml
- new Pod for fedmsg-relay
- hub address is tcp://fedmsg-relay.continuous-infra.svc:4001
- pub address is tcp://fedmsg-relay.continuous-infra.svc:2003
- Jenkins jms messaging provider is called: fedora-fedmsg-devel
- Added 2 new template Jenkins jobs to test functionality: fedmsg-devel-sender-test and fedmsg-devel-receiver-test
- renamed Jenkins templates
Note: call to create-fedmsg-relay.sh needs to be added to ansible dev-setup
> FedMsg Relay Pod for dev env

- config/Dockerfiles/singlehost-test/package-test.sh
This is mostly in preparation of the systemd pipeline. If the test subject image has no python, only python3, we will need the ability to pass this in to the playbook command.  This is the case with rawhide images. With this change, we could just define a variable python3=yes pre container call and everything should work.
> Add ability to use python3 for package tests

- dev_setup/README.md
- dev_setup/playbooks/group_vars/all/global.yml
- dev_setup/playbooks/roles/minishift/defaults/main.yml
- dev_setup/playbooks/roles/minishift/tasks/main.yml
This will let users configure how large the rootfs needs to
be for pods in minishift
> Add ability to set minishift base device size

- Jenkinsfile
- src/org/centos/pipeline/PipelineUtils.groovy
If setStageEnvVars() is the last item in a stage section
and there is no submap for the stage, then Jenkins will throw
a cryptic 'java.io.NotSerializableException: org.codehaus.groovy.runtime.NullObject' error
This is due to the unchecked .get() that otherwise is silently ignored
if another step comes after setStageEnvVars() in a stage.
> Protect against null object errors

- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
- config/Dockerfiles/inquirer/Dockerfile
- config/Dockerfiles/inquirer/find_nvr.sh
- config/Dockerfiles/inquirer/poller.sh
- config/Dockerfiles/ostree-boot-image/ostree-boot-image.sh
- config/Dockerfiles/singlehost-test/Dockerfile
- config/Dockerfiles/singlehost-test/main.yml
- config/Dockerfiles/singlehost-test/standard-inventory-qcow2
- config/Dockerfiles/singlehost-test/upstreamfirst-test.sh
- config/s2i/inquirer/inquirer-buildconfig-template.yaml
- playbooks/rpm-verify.yml
All of these changes are necessary in order to add support for the systemd pipeline.  However, I did not include any of the systemd Jenkinsfile type files, I will in a follow up PR.
Things done in this PR:
- Add sym link to cloud-image-compose script so we have a reliable file to call in the Jenkinsfile
- Add the inquirer container. This container has two scripts: one polls a url, waiting for it to exist, exiting if it does not by $timeout; the second gets the NVR of an rpm using repoquery from a $rpm_repo
- ostree-boot-image changes: Only run the commit verify playbook if $commit is defined; if $expected and $package are both defined, run the rpm-verify playbook (new) that will check that the running nvr of the $package rpm on the host is $expected
- Add a modified beakerlib role …
> Add necessary changes to add systemd pipeline

- config/s2i/jenkins/continuous-infra-create-openshift-project
The patch for adding dev_setup forgot to rename these template files.
> config/s2i/jenkins: rename jenkins bc templates

- config/Dockerfiles/inquirer/Dockerfile
- config/Dockerfiles/inquirer/poller.sh
Lost that part of my script with a rework. If the remote_file is never found, we need to exit nonzero once we hit the timeout, as that is kind of the entire point.
> Exit poller nonzero if timeout hit

- config/Dockerfiles/singlehost-test/Dockerfile
I somehow didn't have all the official requirements listed in the Dockerfile install and never hit a bug because they have just always been there luckily, so fixing it to be cleaner.
> Add all reqs for standard-test-roles Dockerfile

- config/Dockerfiles/singlehost-test/Dockerfile
dnf copr is no longer available with the base install of dnf it seems, so add dnf-plugins-core to get it.
> Add dnf-plugins-core to container

- JenkinsfileTrigger
- utils/package_checker.py
This will first try to use the upstream package list json to determine if the package is part of atomic. If the checking of upstream fails, it falls back to checking our static list.
> Get package list for trigger from upstream

- config/s2i/jenkins/jenkins-persistent-buildconfig-template.yaml
- config/s2i/jenkins/slave/Dockerfile
Since v3.7 of openshift, there is the possibility for breakage in
backwards compatibilty when using the v3.7 'oc' command with a 'v3.6'
master.
This change forces us to use the v3.6 oc binary
This is a better practice in any event, since we should not be pointing
to a 'latest' tag.
See https://github.com/openshift/jenkins-sync-plugin/issues/173 and https://github.com/openshift/jenkins/issues/477 for details
> Fix slave FROM tag and set JVM arch for master

- config/s2i/jenkins/jenkins-persistent-buildconfig-template.yaml
This has to be done if your Jenkinsfile lives in a repo that your jenkins master cannot securely connect to. Unless there are any drawbacks to this (Scott?), I think we should make this change.
> Allow insecure git checkout for Jenkinsfile

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
coreutils requires this, hopefully it doesn't break anything else
>  FORCE_UNSAFE_CONFIGURE=1 in rpmbuild

- config/Dockerfiles/singlehost-test/package-test.sh
There was a failure due to standard-test-roles being too old in the container, so I was asked to update standard-test-roles to latest each time. Kind of goes against the rules of how OpenShift should work in my opinion, so instead of stripping standard-test-roles from the Dockerfile and doing dnf -y install standard-test-roles in the shell script, I decided to do an update in the script and rpm -q so they can see the version in case there is no update available.
> Update standard-test-roles before running tests

- config/Dockerfiles/singlehost-test/upstreamfirst-test.sh
I want to be able to pass in TEST_SUBJECTS and use that instead of always relying on the hardcoded value.
> Make test_subjects potentially variable in upstreamfirst tests

- config/Dockerfiles/singlehost-test/upstreamfirst-test.sh
I want to be able to leverage the error code of 2 if the ansible-playbook fails, so I need *only* the ansible-playbook call to result in the script returning 2.
> Change upstreamfirst error codes

- config/s2i/jenkins/master/plugins.txt
Both of these are currently installed on our master and needed for the workflow, so add them to plugins.txt. Note, both of these have updates available, but I put the versions that are currently installed on the upstream master, not latest.
The ghprb plugin is the github pull request builder plugin which we obviously need for all the stage stuff.
The lockable-resources plugin is for the lock() function in the JenkinsfileStageMerge job
> Add installed plugins to plugins.txt

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
In scripted pipeline, you have no way to mark a stage as skipped like you do in declarative. To my google searching, it simply isn't supported. But, with this function, you can. To do it, you would do something like this
stage('foo') {
if (skipme) {
pipelineUtils.skip('foo')
}
}
@robnester-rh Do I need the import in the vars file too or just the src/..... .groovy file?
Also note that this requires a groovy script approval (for those of you using s2i). It is staticMethod org.jenkinsci.plugins.pipeline.modeldefinition.Utils markStageSkippedForConditional java.lang.String
> Add skip stage function

- dev_setup/README.md
- dev_setup/playbooks/roles/minishift/tasks/main.yml
- Remove setting that allows for containers bigger than 10GB for
devicemapper (no longer used in newer version of docker)
- Update README - Don't need to have default values on the command line
> Remove docker storage driver setting for minishift

- config/Dockerfiles/singlehost-test/package-test.sh
Currently, --tags atomic is hardcoded. Make it so we can override that for upstream all packages pipeline
> Make tag configurable

- config/Dockerfiles/rpmbuild/pull_old_task.sh
Not sure if it is the version of bash or what, but it is putting one dir inside the other, which is not the behavior I see locally, so be specific
> Bash logic

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
The current build name and description functions have no flexibility. This one lets us pass in any strings we want
> Add function for custom build name and description

- JenkinsfileTrigger
Example:
https://apps.fedoraproject.org/datagrepper/id?id=2018-16e4cc3d-4203-47dd-bc24-9ffd5debee9f&is_raw=true&size=extra-large
> only trigger atomic pipeline on prod repos

- config/Dockerfiles/cloud-image-compose/Dockerfile
- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
Sometimes, the fed_repo isn't the package name, such as with krb5. So, I was asked to discover the rpms to install like this instead.
> Better package discovery

- config/Dockerfiles/elasticsearch/elasticsearch.yml
- config/s2i/elasticsearch/es-ephemeral-buildconfig-template.yaml
This allows the long running container to run without privileged mode set to true.
> adding init container. removing privileged from main container

- config/Dockerfiles/rpmbuild/koji_build_pr.sh
- config/Dockerfiles/rpmbuild/pull_old_task.sh
- config/Dockerfiles/rpmbuild/rpmbuild-local.sh
Have seen some weird behavior where download-build --task-id foo fails, but download-task foo works
> If download-build fails, use download task

- config/s2i/jenkins/slave/Dockerfile
LinchPin now has a job for doing continuous releases. The Jenkins slave needs to have a few additional packages to run it, however.
> Update slave Dockerfile for linchpin release job

- config/Dockerfiles/singlehost-test/rpm-verify.yml
- config/Dockerfiles/singlehost-test/verify-rpm.sh
We can't use package name to verify rpms because the src rpm name doesn't always match the rpms we install. So instead, provide the location to the rpms and check that at least one rpm from that repo is installed.
> Update rpm verifier

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
Pretty gross if you ask me. They renamed *just* the f28's cloud image directory.
> They moved qcow2 locations

- JenkinsfileTrigger
- utils/package_checker.py
Currently, if you hear a commit to the cockpit repo for example, you check the atomic host json and say there are no packages named cockpit, so do not trigger. However, there are rpms in atomic host from the cockpit distgit repo, they just aren't named "cockpit," they are "cockpit-foo." So, query the PDC if we don't find it in the json originally to see if the package is one of these examples. This adds ~20 seconds sadly.
> Add better checking in the trigger

- config/s2i/jenkins/master/configuration/jobs/recycle-openshift-builds/config.xml
- utils/recycleOCBuilds
Once a day, this job will remove all builds in the openshift instance with -build in their name that are in the completed state. I didn't do the error state ones in case someone wants to see the log output. I also didn't put any age restrictions because I don't see the point in keeping around a successfully completed build for any time at all.
> Add oc build recycler

- utils/package_checker.py
/pkg/ works with cockpit, so I thought it was solved, but not with vim. We need /srcpkg/ instead
> Use srcpkg not pkg

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
May not need this if the job you have quickly created works as expected
Or maybe we leave this until rawhide starts passing again
> Use different qcow2 image location

- config/Dockerfiles/singlehost-test/Dockerfile
To make sure latest bits are pulled in when building.
Important usually for fast-moving standard-test-roles updates.
> singleshost-test: refresh dnf cache

- config/Dockerfiles/singlehost-test/package-test.sh
Now that we tee the output, we need pipefail, or else the playbook command will never fail, which breaks our logic for finding if things were unstable or not
> Set pipefail before running test

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
Include -devel packages, because some of the package build only these
(i.e. rust-xattr)
> cloud-image-compose: improve package filtering

- config/Dockerfiles/singlehost-test/rpm-verify.yml
I see some failures for python2-dnf not being present on the qcow2 image, which makes the dnf module not work
> Install python2-dnf when necessary

- config/Dockerfiles/singlehost-test/package-test.sh
Some of the shared tests need this information. This is a quick fix for
the community. We will later standardize the name.
> singlehost-test: expose nvr for tests

- utils/recycleOCBuilds
Recycles pods in error or evicted state that are older than 6 hours old. Pod life is in m when minutes, then h for hours, then d for days, so I delete if it contains d, and if it contains h I make sure the integer > 6.
> Recycle error pods too

- utils/recycleOCBuilds
6 hours is simply not good enough for some of our projects. They need pods removed more quickly
> Change 6h limit to 1h

- src/org/centos/pipeline/PipelineUtils.groovy
Because the oc get pods has four things in it separated by spaces, so the if statement complains about too many arguments. Since we are just grepping for text anyways, we can just delete all the spaces in the output to avoid wrestling with more quoting and variable expansion.
> Remove spaces in pod output

- config/Dockerfiles/singlehost-test/Dockerfile
Workaround for https://github.com/ansible/ansible/issues/43884.
> singlehost-test: use older ansible from centos extras

- config/Dockerfiles/singlehost-test/package-test.sh
- config/Dockerfiles/singlehost-test/verify-rpm.sh
If STR update fails, continue test execution with already installed STR version.
> retry to update STR 5 times, if can't update do not fail test execution

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
If you create podTemplate A then podTemplate B, podTemplate B will include all containers from A unless you call this before B's creation.
> Add clear template names function

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
This is actually from rob's PR 455.  It's needed when running
in parallel.  env is shared.
> Update executeInContainer with optional vars to be passed in.

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
F29 upstream pipeline should use qcow2 from https://jenkins-continuous-infra.apps.ci.centos.org/view/all/job/fedora-f29-image-test/lastSuccessfulBuild/artifact/Fedora-29.qcow2
> add support for pipeline to use F29 qcow2

- Jenkinsfile
Recently there were several jobs stuck in the pipeline in the test
execution step. The problem seems to be caused by insufficient memory.
Specifying minimum/maximum cpu/memory resources should fix that.
> Define resources for the singlehost-test container

- config/Dockerfiles/singlehost-test/rpm-verify.yml
This should make easier to debug in case some package is not installed.
Example of current playbook output:
+ ansible-playbook -v --inventory=/usr/share/ansible/inventory/standard-inventory-qcow2 --extra-vars subjects=/workDir/workspace/fedora-rawhide-build-pipeline/images/test_subject.qcow2 --extra-vars artifacts=/workDir/workspace/fedora-rawhide-build-pipeline/logs --extra-vars rpm_repo=/etc/yum.repos.d/standard-test-roles /tmp/rpm-verify.yml
++ pwd
+ tee /workDir/workspace/fedora-rawhide-build-pipeline/logs/rpm-verify-out.txt
Using /etc/ansible/ansible.cfg as config file
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: …
> nvr check saves list of installed packages

- config/Dockerfiles/singlehost-test/package-test.sh
STI only uses the inventory file as script so it has to be executable, so make sure pipeline does not execute the playbook using inventory with wrong permission.
> exit with error if tests/inventory is not executable

- config/Dockerfiles/str-container-test/Dockerfile
With Fedora 28, the pod is created and it fails instantly with "The agent has not been fully initialized yet." For some reason, I don't see this with Fedora 27. Also, with the Fedora 27 container, I have confirmed I don't need all the systemd hacking, /usr/sbin/init with the no VOLUME line seems to be sufficient.
> Fix str-container-test container

- JenkinsfileTrigger
- config/s2i/jenkins/master/configuration/jobs/ci-pipeline-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedmsg-devel-receiver-test/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedmsg-devel-sender-test/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedora-build-pipeline-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedora-pr-added-pipeline-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedora-pr-new-pipeline-trigger/config.xml
- config/s2i/jenkins/master/plugins.txt
- src/org/centos/pipeline/PipelineUtils.groovy
We need jms-messaging-1.1.1 to send out nested arrays on fedmsg. These are the changes to resolve the syntax changes between 1.0.36 and  1.1.1
We can no longer have two topics for one trigger job, so some job(s) had to be split.
> Updates for jms-messaging-1.1.1

- config/Dockerfiles/singlehost-test/Dockerfile
standard-test-source role does not work on ansible 2.5.8
> use ansible 2.7.7

- config/s2i/jenkins/slave/Dockerfile
- src/org/centos/pipeline/PipelineUtils.groovy
We keep getting java socket timeouts when oc start-build begins, so the --wait is lost and the build proceeds with an unfinished image, which fails. This seems to work around it.
> Workaround socket timeout losing --wait

- src/org/centos/pipeline/PipelineUtils.groovy
This is helpful if the project has multiple development branches
at the same time.
> Allow for custom stable tags to be used

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
We remove awk from the first repoquery to save the entire capability. Then, we perform another repoquery to see if any of the rpms in the repo meet that capability, which would mean there is a conflict. Seems to work in my local testing.
> Check if any rpms satisfy conflict capability instead

- utils/recycleOCBuilds
This fails if ```oc get pods | grep ``` returns nothing as well. Since they all will have OR true attached to them, I removed the error catching too.
@bgoncalv
> Don't fail on oc delete pod either

- config/Dockerfiles/singlehost-test/package-test.sh
yaml callback plugin is available sinse Ansible 2.5: https://docs.ansible.com/ansible/latest/plugins/callback/yaml.html
It improves readability, especially for cmd stages of the execution.
Example output:
```
TASK [standard-test-basic : Execute tests] ************************************************************************************************************************************************************************
changed: [localhost] => (item={'smoke': {'dir': 'python/smoke', 'run': 'VERSION=3.7 ./venv.sh'}}) => changed=true 
cmd: |-
if [[ -z ${TEST} ]]; then
echo "FAIL: Test case name is not set" >> /tmp/artifacts//test.log
exit
fi
if [[ -z ${TEST_DIR} ]]; then
echo "FAIL: Test directory for $TEST not found" >> /tmp/artifacts//test.log
exit
fi
if [[ -z ${TEST_CMD} ]]; then
echo …
```
> Fast fix to improve readability for ansible logs

- config/Dockerfiles/singlehost-test/Dockerfile
- config/Dockerfiles/singlehost-test/package-test.sh
- config/Dockerfiles/singlehost-test/sync-artifacts.yml
Make sure artifacts are synced after tests are executed,
even if test playbook didn't do it or got aborted
> force sync artifacts in the end of test execution

- config/s2i/jenkins/jenkins-persistent-buildconfig-template.yaml
https://pagure.io/fedora-ci/general/issue/104
Our cluster is openshift 3.6 and requires the 3.6 cli per pagure fedora-ci issue 104
Also, a quick glance shows other images related to jenkins are also still on 3.6, which is expected given our cluster:
https://github.com/CentOS-PaaS-SIG/ci-pipeline/blob/master/config/s2i/jenkins/slave/Dockerfile#L1
> Proposed fix for Fedora CI issue 104
