- config/package_list
- jobs/test.yaml
- verify that the branch is a development branch
- verify the package is in our list
> Limit which branch and packages we work on

- jobs/test.yaml
Not sure of how much value add there is but this will run the test anyway
> Add fedpkgabidiff test to test.yaml jjb

- utils/pull_requests.py
There is a plugin github-pull-request but that requires write access.
This will work with just a valid log in.
> Pull request monitor for jenkins jobs that want to trigger off of changes to PR's in github.

- jobs/service-jobs.yml
- Running this on the slave requires we run this in a virtual environment
- Fix macro name not to have a $ in front
> Update jobs to use shining-panda virtualenv for python

- jobs/rpmbuild.yaml
Bill and I used the same builder name which broke jjb update.  Changing mine
> change builder name

- jobs/rpmbuild.yaml
Forgot to fix publisher name duplication as well last PR
> fix duplicate publisher names

- config/package_list
> remove gtk from package list

- tasks/rpmbuild-test
Also sorted file to make it a little cleaner
> add ISO8601 timestamp to each repo in manifest.txt file

- tasks/rpmbuild-test
> Use cp for log transfer

- jobs/rpmbuild.yml
> fix double {}

- jobs/ci-pipeline-defaults.yml
- jobs/ostree-compose.yml
- jobs/rpmbuild.yml
Allows us to customize this per job.
> Move which variables to export into a macro/variable

- jobs/ostree-compose.yml
- tasks/ostree-compose
- tasks/ostree-image-compose
Added trigger to ostree compose to call ostree image compose.
> add ostree image compose job

- utils/pr-commenter.py
Utility script to comment on github pull requests that does not require write access, just a token to authenticate as.
> Add python script to comment on github repos

- jobs/ostree-compose.yml
Don't hardcode the branch to rawhide.
> Require branch to be passed in.

- jobs/ostree-compose.yml
Also do calculations based on last Successful build.
> Update trigger to check for a previous build with the same fed_branch.

- utils/pr-commenter.py
dont return null string if one of the comment text files DNE
> Fix small logic problem in pr commenter util

- config/libvirt-setup/roles/libvirt-system/tasks/main.yml
- config/libvirt-setup/roles/libvirt-system/tasks/vm-destroy.yml
- config/libvirt-setup/roles/libvirt-system/tasks/vm-import.yml
- config/libvirt-setup/roles/libvirt-system/tasks/vm-init.yml
- config/libvirt-setup/roles/libvirt-system/tasks/vm-storage.yml
- config/libvirt-setup/roles/libvirt-system/templates/add_account.sh
- config/libvirt-setup/roles/libvirt-system/templates/cloud-config/meta-data
- config/libvirt-setup/roles/libvirt-system/templates/cloud-config/user-data
- config/libvirt-setup/roles/libvirt-system/templates/hosts
- config/libvirt-setup/setup-libvirt-image.yml
- config/libvirt-setup/setup-system.yml
- jobs/ostree-compose.yml
- tasks/ostree-boot-image
- tasks/ostree-boot-verify.yml
- tasks/ostree-compose
- tasks/ostree-image-compose
This will boot the last generated qcow2 image and optionally
update to the passed in $COMMIT.  Actually, it doesn't do the update
yet, but it will soon. :-)
> Add ostree compose boot sanity job.

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
This PR takes care of the logic for the fields in the defined fedmsgs, there is nothing here for the actual sending of the message as this needs to be set up via UI for now.
> Define fields for the fedmsg for rpmbuild

- jobs/ostree-compose.yml
- tasks/ostree-boot-image
fix ssh permissions and ansible calls.
> lots of little fixes to make it work

- jobs/kernel-f25-kt0.yml
- jobs/kernel_trigger.yml
- tasks/kernel-kt0
- utils/kernel_install.yml
All this does for now is check that the kernel installs, but eventually we will put more testing here (hopefully ltp/lite soon)
> Add jobs to provide framework to run tests on pipeline built kernels

- jobs/ostree-compose.yml
- tasks/ostree-boot-verify.yml
- tasks/ostree-image-compose
> put ostree delete and add at the %end

- tasks/kernel-kt0
> fix typo in utils filename

- tasks/kernel-kt0
- tasks/ostree-boot-image
Saw the error from subject in console output log, so thinking we need this
> mkdir: cannot create directory ‘host_vars’: File exists

- tasks/kernel-kt0
> Change hostname to not collide with other jobs

- config/package_list
> add atomic-devmode to package list

- tasks/kernel-kt0
> cleanup kernel install slaves

- jobs/ci-pipeline-defaults.yml
- jobs/service-jobs.yml
- Added new sha
- Remove duplicate of logrotate since that is deprecated
> Update SHA for JJB for builders and publishers

- jobs/atomic-host-tests.yml
- tasks/atomic-hosts-tests
- tasks/kernel-kt0
> Small fixes to kernel and atomic-host-tests tasks

- jobs/ostree-compose.yml
- jobs/rpmbuild.yml
- tasks/ostree-image-compose
messages aded for ostree-compose, ostree-compose-image and ostree-compose-boot-sanity
> Publish messages on the bus at runtime and completion.

- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
Thanks for spotting this user B
> fix fedmsg provider name

- tasks/atomic-host-tests
Forgot to add some closing stuff after the for loop and the .txt on the inventory file
> Add closing parts of xunit to atomic-host-tests

- tasks/ostree-boot-verify.yml
We shouldn't have got past the first ssh connect check but
sometimes we do.
> Attempt to work around sparadic connectivity issues.

- tasks/kernel-kt0
> wait for host to come back before scp in kernel kt0

- tasks/kernel-kt0
Oops.  This is why we review PRs.  Goodbye 6 hours 27 minutes
> Forgot to give an argument to ping -W

- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
Unsure if jjb accepts not having msg-content defined whatsoever like I have it.  Would love confirmation, or we will see when the service job picks it up...
> Fix fedmsg fields to be in msg props

- jobs/atomic-host-tests.yml
- jobs/ostree-compose.yml
- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
Put key value pairs in message properties for the rest of our jobs' fedmsgs and add branch in to the rpm ones.
> Fix rest of fedmsgs

- README.md
- Updated fields
- Everything in message properties
- message context is blank
> Update of fedmsgs which are more accurate to what we publish

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
> Append # of commits and short sha to rpm spec file release

- jobs/rpmbuild.yml
- jobs/rpmbuild_trigger.yml
> Change to variable topic so we have complete topics at last

- README.md
This lists what fedmsg topics relate to which pipeline stages
> Update readme with topics in stages description

- Jenkinsfile
- Converted all individual jobs from JJB into pipeline
- Checking for variables
- Make libraries out of repeated functions
Note: This will probably need to be refactored as we get used to using pipelines
- Remove echo and prints
- reduce redundant defs of vars where possible
> Jenkins 2.0 Pipeline file

- Jenkinsfile
- jobs/service-jobs.yml
- Removed extra defining of current_stage on teardown
- Remove quotes around ${TARGETS}
- change service_jobs to force update --ignore-cache
> Changes to pipeline and service job

- Jenkinsfile
- Since the JMS Messaging plugin has issues at the moment we should remove the properties declaration
> Remove Job Properties in the pipeline

- playbooks/libvirt-setup/roles/libvirt-system/templates/cloud-config/user-data
This should allow the ansible synchronize module to work.
> Create admin user with passwordless sudo

- jobs/atomic-host-tests.yml
- jobs/ci-pipeline-defaults.yml
- jobs/rpmbuild.yml
- tasks/rpmbuild-test
> enable concurrency for rpmbuilding and atomic testing

- jobs/ci-pipeline-defaults.yml
> Rsync wont create dirs two levels down

- tasks/rpmbuild-test
> Fix locks and add some sudo to docker commands

- jobs/rpmbuild.yml
I think the service job is failing for me not defining "option" in throttle
> Fix throttle syntax

- playbooks/ostree-boot-verify.yml
Junit sorts the tests by name by default so to keep them in execution
order I number them.
> number the ansible tasks

- Jenkinsfile
- RSYNC issues of content
- Setup a global current_stage so we can use it to teardown resources
- setup a MAIN_TOPIC to change to publish on a different topic
- Update playbook locations
> Fix Jenkinsfile Pipeline issues

- Jenkinsfile
- jobs/rpmbuild_trigger.yml
- Add exit to Jenkinsfile on shell steps
- Echo current stage and step we are in
- current-parameters: true
- Add CI_MESSAGE into job.properties
> Update Jenkinsfile (pipeline) and more debug

- tasks/rpmbuild-test
> dont rsync if rpmbuild failed

- Jenkinsfile
- jobs/rpmbuild_trigger.yml
- Add branch to current.Display
- Add CI_MESSAGE to its own file in old rpmbuild-trigger job
> Update pipeline to display branch

- Jenkinsfile
- JenkinsfileTrigger
- Single job pipeline for the trigger
- Pipeline for f26 right now for rest of the pipeline
> New Jenkinfile for rpmbuild-trigger

- Jenkinsfile
- Added the credential in our openshift jenkins
- reference it for allocation of duffy and syncing
> Add support for duffy.key now that we are in Openshift

- Jenkinsfile
- I used plain text and not a var
- Also changed it to be uppercase
> Fix variable for fedora-atomic-key

- Jenkinsfile
- Needed both keys placed on the slave
- Changed duffy-key to be a file
- All are now files placed on the slave at runtime
> Pulled in private and public keys to mimic ci.centos.org

- Jenkinsfile
- tasks/ostree-compose
- tasks/ostree-image-compose
The mv seems to not be working for compose-image
> Add a link to the logs directory

- Jenkinsfile
- Skip generating images since it causes issues
- Also add stage message to checkLatestImage
Once this is split into libs for each stage
this will make more sense
> Skip creating images atm

- config/s2i/jenkins/master/plugins.txt
project-inheritance:2.0.0
promoted-builds:2.28.1
> Remove plugins from image that caused rebuild problems

- Jenkinsfile
- boot-sanity in Jenksfile did not have this in
tasks.env
> Add "export ANSIBLE_HOST_KEY_CHECKING="False"

- config/Dockerfiles/ostree_image_compose/ostree-image-compose.sh
- tasks/ostree-compose
- tasks/ostree-image-compose
add exit 0 to clean up routine.
ignore return codes for now.
> Just put the kickstart and tdl in the logs directory to begin with

- Jenkinsfile
- Updated archive call to grab *.groovy in subdirs
> Archive all groovy prop files that get created

- Jenkinsfile
- JenkinsfileTrigger
- Create sendMessage method and just pass messageProperties
and message context
- Add debug to see the state of the environment
during boot-sanity
- Remove loading of ostree_props again which is not
necessary after stage ostree-compose loads them
> Update how we send messages and debug

- Jenkinsfile
- JenkinsfileTrigger
- sendMessage method put in place
- changed OSTREE_BRANCH and commit not to set default :-
- fixed indenting and formatting
> Updated messaging and fixed variables for groovy

- Jenkinsfile
if (env.OSTREE_BRANCH == null) {
env.OSTREE_BRANCH = ""
}
> Set env to empty strings if they don't exist

- Jenkinsfile
- Needed to ignore atomic-host-tests
> Removed wrong xUnit step

- Jenkinsfile
- uncomment checkLatestImage
- remove debug for env inside of ostree-boot-sanity
> Add creating images back and remove debug of env

- Jenkinsfile
- JenkinsfileTrigger
- README.md
- Removed unnecessary queuing messages
- Added ostree.props loading into ostree-image-compose
- When calling pipeline from trigger add MSG_PROVIDER
> Update README with accurate messages

- Jenkinsfile
- system-setup.yml
We can probably use this one for all for
consistency since the only difference is ara
> Use correct playbook for ostree-image-boot-sanity

- JenkinsfileTrigger
- Until we get https://github.com/openshift/jenkins/pull/337 merged
> Allow triggers to run on master

- config/Dockerfiles/package_tests/image/Dockerfile
- config/Dockerfiles/package_tests/image/image_package_test.sh
Will raise separate PR for the ansible container
> Revamp image package test container for new invocation

- README.md
- This will need tuning for image and functional test messages
but at least captures the other data
> Update messages to be accurate to what we publish

- Jenkinsfile
- JenkinsfileTrigger
- Added boolean GENERATE_IMAGE
- Also archive the trigger.downstream file
> Force generation of the atomic host image

- Jenkinsfile
- JenkinsfileTrigger
- README.md
- Updated README with correct order and examples from live message
stream
- Fixed TOC
- Added a message legend
- Put the trigger pipeline on production main topic
- Removed N/A and use '' instead for compose_rev when running
> Updated documentation and fixed a couple of value issues in messages

- README.md
- Just copied what we have for package messages and changed the topic
> Fix test.functional messages based on nits

- Jenkinsfile
- JenkinsfileTrigger
- add echo of exception
- remove properties()
> Cleanup stages, add exception echo, remove properties

- playbooks/roles/ara/tasks/main.yml
- Latest failures have to do with install of ara latest
> Issue with ara 0.14.0 so pinning to 0.13.0

- JenkinsfileTrigger
- needs some testing reverting the change
> withEnv does not work as expected

- Jenkinsfile
- This lays the groundwork for adding containers for testing
> Inline the definition of pod and container templates

- config/openshift/pipelines/rpmbuild/Jenkinsfile
- config/openshift/pipelines/rpmbuild/rpmbuild-pipeline.yaml
> rpmbuild pipeline

- config/package_list
rpm-ostree has a nice integration testsuite which would be great to run
in the CI pipeline. Add it to the package list.
> package_list: add rpm-ostree

- Jenkinsfile
- This caused a recent failure
https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/18/console
> Remove backticks from the fedmsg_fields.txt

- tasks/rpmbuild-test
I removed a variable definition in my PR.  Need to put it back
> Hotfix rpmbuild test

- tasks/rpmbuild-test
Reverts CentOS-PaaS-SIG/ci-pipeline#284
> Revert "Hotfix rpmbuild test"

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- tasks/rpmbuild-test
Reverts CentOS-PaaS-SIG/ci-pipeline#257
> Revert "Improve rpmbuild container and have it do the rsync as well"

- Jenkinsfile
- config/Dockerfiles/ostree_compose/ostree-compose.sh
- config/Dockerfiles/ostree_image_compose/ostree-image-compose.sh
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- config/Dockerfiles/rsync/rsync.sh
- tasks/atomic-host-tests
- tasks/kernel-ltp
- tasks/ostree-boot-image
- tasks/ostree-compose
- tasks/ostree-image-compose
- tasks/rpmbuild-test
This should make it easier to create staging pipelines and to
run these on ad-hoc setups.
> Remove all hardcoded paths.

- Jenkinsfile
rpmbuild job still needs to kinit using the example in the commit.
> Added fedora keytab and Principal info.

- Jenkinsfile
Include default for FEDORA_PRINCIPAL
> Move String Param to be with other string params

- Jenkinsfile
- vars/atomicHostTests.groovy
- vars/ostreeBootSanity.groovy
- vars/ostreeCompose.groovy
- vars/ostreeImageBootSanity.groovy
- vars/ostreeImageCompose.groovy
- vars/rpmBuild.groovy
- Updated Jenkinsfile and libs
> Remove RSYNC_PASSWORD from being echoed

- Jenkinsfile
- Jenkinsfile-sl-pipeline
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/cicdPipeline.groovy
- Added nvr, original_spec_nvr to Jenkinsfile
and PipelineUtils
- Set defaults for nvr and original_nvr_spec in cicdPipeline
and Jenkinsfile
- Exclude artifacts jobs.props and job.props.groovy
- Comment out pipeline.complete message until pingou is ready
for it
> Update to Jenkins-sl-pipeline, Jenkinsfile, cicdPipeline

- Jenkinsfile
- Put back original code to parse the message with subs
> Revert change so the pipeline is not blocked

- Jenkinsfile
Updated python script in Jenkinsfile to reflect changes made in
rpmBuild.groovy
> UPDATE python script in Jenkinsfile

- Jenkinsfile
- Jenkinsfile-sl-pipeline
- JenkinsfileTrigger
- also removed extra send message
> Correct Build Status in try()

- config/Dockerfiles/rpmbuild/Dockerfile
> Add another package we will need to authenticating to submit builds to koji

- Jenkinsfile
- vars/cicdPipeline.groovy
- ANSIBLE_HOST_KEY_CHECKING
- Remove null cehcks for OSTREE_BRANCH, image2boot, imagename
This is only temporary until Rob's refactor occurs
> Define some default environment variables and switch to stage topic for cicdPipeline.groovy for now

- JenkinsfileTrigger
- Add Retry()
- Update description to denote TRIGGER FAILURE
> Better protect triggering of Pipeline Builds

- Jenkinsfile
Could be other issues still.  But this is minimum.
> Add missing variables to atomic-host-tests stage.

- Jenkinsfile
- **/logs/ansible_xunit.xml
This worked:
https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/190/
> Change the directories and file we check for xUnit

- config/s2i/jenkins/continuous-infra-jenkins-master-s2i-template.yaml
- Replicate https://github.com/openshift/origin/pull/16183
> Add Jenkins SERVICE NAME

- Jenkinsfile
We talked about this today, figure we still do want it turned on here, so here is the appropriate change.
> Turn on xunit consumption for ostree-boot-sanity

- Jenkinsfile
need to make the change directly in ssh config.
> Not enough coffee yet. We are talking about rsync not ansible.

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
> Arch override koji builds

- playbooks/roles/rdgo-system/tasks/main.yml
so better get the order right.
> ansible playbook iterates through installs

- tasks/ostree-boot-image
eventually this logic needs to move into one of the containers.
> sudo needed for updating symlink.

- README.md
- Updated messages based on live data from the message bus
- Added pipeline.complete message
- Added UNSTABLE as a possible status for failed tests
This implies things need to be analyzed.
> Update README.md about message

- config/s2i/jenkins/continuous-infra-jenkins-master-s2i-template.yaml
- See https://github.com/openshift/origin/pull/16597
> Remove the setting for the JVM architecture

- README.md
I unwisely added this fix in with another larger PR that I had to abandon, so fixing it again.
> Recorrect README

- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
> Echo original_spec_nvr earlier

- utils/pull_requests.py
Add two new options: --whitelist and --limit-whitelist
The first takes a file containing line-delimited github PR author names.
When specified, a PR will only be considered for triggering if the
author is in the referenced whitelist file.
The second option is related to --limit-keyword and requires --keyword.
When specified, it requires the keyword-commenter must be in the
whitelist file (the PR author is ignored).
Some other small changes were made to function-parameters to permit
simpler passing of options.  Also simplification of the triggering
conditional was made which will better support future addition of
conditions.
Signed-off-by: Chris Evich <cevich@redhat.com>
> whitelist check for PR author or keyword commenter

- Jenkinsfile
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
- Query datagrepper to make sure message sent
- Create an artifact that contains all messages sent during build
> Add audit of all messages that are sent

- config/s2i/jenkins/master/configuration/init.groovy
> Update fedora-fedmsg providers

- Jenkinsfile
- needed for pod name and label
- should be used for messaging to segregate messages from branches
> Add ExecutionId

- Jenkinsfile
- JenkinsfileStageMerge
- config/Dockerfiles/package-test/Dockerfile
- config/Dockerfiles/package-test/integration-test.sh
- config/Dockerfiles/package-test/standard-inventory-qcow2
- Addresses https://pagure.io/standard-test-roles/pull-request/47
> Patch standard-inventory-qcow2 for integration tests

- Jenkinsfile
- tasks/ostree-image-compose
> fix props file path

- config/s2i/jenkins/master/configuration/hudson.plugins.ircbot.IrcPublisher.xml
- config/s2i/jenkins/master/plugins.txt
- plugins ircbot:2.30, instant-messaging:1.35
- XML config for IRC
> Add IRC Global Bot configuration

- config/Dockerfiles/singlehost-test/Dockerfile
- config/Dockerfiles/singlehost-test/integration-test.sh
- config/Dockerfiles/singlehost-test/package-test.sh
The inventory for the integration tests has gone awry since Bill's PR merged. First shot at fixing it
> Cleaner ANSIBLE_INVENTORY

- Jenkinsfile
- config/Dockerfiles/ostree_compose/ostree-compose.sh
- config/Dockerfiles/rpmbuild/rpmbuild-test.sh
- config/Dockerfiles/singlehost-test/integration-test.sh
- config/Dockerfiles/singlehost-test/package-test.sh
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
This should cause us to push to rawhide's actual release on artifacts.ci instead of "rawhide" or "master"
> Never push to rawhide

- Jenkinsfile
- config/Dockerfiles/ostree-boot-image/ostree-boot-image.sh
- config/Dockerfiles/ostree-image-compose/ostree-image-compose.sh
- playbooks/roles/libvirt-system/tasks/vm-import.yml
also removed the $? checking since we have set +e and it won't be executed
> If provisioning fails then take a screen shot of the failed system.

- config/Dockerfiles/linchpin-libvirt/Dockerfile
- config/Dockerfiles/ostree-boot-image/Dockerfile
> Force rebuild of 2 containers for prod

- config/Dockerfiles/linchpin-libvirt/Dockerfile
Summary:
$Subject
Updated origin-test binaries in paas-sig-ci playbooks
> Updated binaries of origin test rpms in paas-si-ci repo

- Jenkinsfile
- src/org/centos/pipeline/PipelineUtils.groovy
- also protect from getContainerLogsFromPod errors
> Disable E2E tests

- src/org/centos/pipeline/PipelineUtils.groovy
- this will reduce the number of failures due to datagrepper
instabilities.
> Only fail if datagrepper returns NOTFOUND

- config/Dockerfiles/singlehost-test/upstreamfirst-test.sh
See BZs from comments, these always fail on rawhide for now
> Turn off two tests for systemd that fail on rawhide

- dev_setup/README.md
Small typo fix (at least I think you need the -playbook, I did)
> Add the -playbook to the ansible commands

- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
> Add support to cloud-image-compose for local rpm repos

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/rpmbuild-local.sh
> Add rpmbuild local for koji building

- Jenkinsfile
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
Currently, we just get lucky and depend on another function in the library setting topic=
> Add topic as parameter to sendMessage

- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
> Fix cloud image compose baseurl

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
> Add function to check if tests exist

- config/Dockerfiles/singlehost-test/upstreamfirst-test.sh
> Don't default to upstreamfirst testing using python 3

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/pull_old_task.sh
- config/Dockerfiles/rpmbuild/repoquery.sh
Add a script to make sure the repo generated is valid
Add a script to pull an existing koji task and create a repo with its artifacts
> Add more functions to rpmbuild container

- config/Dockerfiles/rpmbuild/pull_old_task.sh
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
> Add fed_ variables for koji task, update checkTests function

- src/org/centos/pipeline/PipelineUtils.groovy
Library has been syntax which breaks everything, so comment out bad code until I fix it
> Hotfix library

- src/org/centos/pipeline/PipelineUtils.groovy
> Fix checkTests function

- Jenkinsfile
- README.md
- src/org/centos/pipeline/PipelineUtils.groovy
Also skip functional test stage entirely if no tests exist
> Change BUILD_URL in messages

- config/Dockerfiles/rpmbuild/pull_old_task.sh
- config/Dockerfiles/rpmbuild/rpmbuild-local.sh
> Provide nvr and original_spec_nvr in new build scripts

- Jenkinsfile
Stage will be present but skipped now
> Legitimately skip functional test stage if tests DNE

- src/org/centos/pipeline/PipelineUtils.groovy
Not sure how we got this far without this being defined honestly
> Need package defined for rsyncing artifacts

- config/Dockerfiles/cloud-image-compose/Dockerfile
- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
- config/Dockerfiles/rpmbuild/rpmbuild-local.sh
Overlooked the fact that I never enabled non rawhide image building in this container
> Enable not rawhide building

- config/Dockerfiles/singlehost-test/package-test.sh
> package tests - Don't fail if you aren't rsyncing

- src/org/centos/pipeline/CIMetrics.groovy
- vars/ciMetrics.groovy
This will allow a pipeline to submit custom tags to influxdb
> Add tags property

- config/Dockerfiles/rpmbuild/Dockerfile
- config/Dockerfiles/rpmbuild/pull_old_task.sh
00:32:17 /var/tmp/rpm-tmp.CSDoBw: line 108: xmlto: command not found
> Add xmlto to rpmbuild container

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/ciMetrics.groovy
- vars/pipelineUtils.groovy
This will allow for reading the package test.log file so the high level test results can be recorded.
> Add read package test log and helper methods in ciMetrics

- config/Dockerfiles/rpmbuild/rpmbuild-local.sh
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
Updating rpm_path in rpmbuild-local.sh also
> adding fileExists function for the rhel and fedora pipelines

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
Example
"path": "/srv/git/repositories/forks/churchyard/rpms/python34.git", 
We don't want to trigger if the git.receive message is from a fork
> Add function to check if fork

- config/Dockerfiles/rpmbuild/koji_build_pr.sh
- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
Needed a new rpm build script as well as a function to inject the other type of fedmsg. Might be some additions later once I get more into triggering off of commits added and comments. Just going with new PRs opened to start
> Add tools needed to build rpms from pagure PRs

- config/Dockerfiles/rpmbuild/Dockerfile
> Forgot to add script to Dockerfile

- config/Dockerfiles/rpmbuild/pull_old_task.sh
> Bring pull_old_task.sh up to speed

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
The less versions of this function we have to maintain the better
> Generalize injectPRVars

- config/Dockerfiles/singlehost-test/package-test.sh
This allows us to pass in a repo besides fedora distgit
> Make test location variable

- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
- config/Dockerfiles/rpmbuild/pull_old_task.sh
this PR will pull fed_branch and branch from pull_old_task and move the logic to the pipeline code.
> Pull setting branch and fed_branch from rpmbuild

- config/Dockerfiles/rpmbuild/pull_old_task.sh
download-task doesn't work on tasks over some age, but this does
> Use koji download-build

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
I think this way leaves the least amount of cleanup and changes to the pipelines to be compatible
> Let checkTests work for PRs

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
> virt-customize -v

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
> Add locking functions

- upstream-fedora-pipeline/AllPackagePipelineStageTrigger
Kind of guessing on the ! changeset thing, but if none of the containers of interest are changed, we have no reason to run, and that has to be incorporated somehow. So, that's what I came up with
> Add stage trigger

- src/org/centos/pipeline/PipelineUtils.groovy
It seems with ''' the parameters passed in to the function don't resolve
> Use double quotes so vars resolve

- src/org/centos/pipeline/PipelineUtils.groovy
With these changes, the function worked for me
I also removed set -x for log size
> More escaping for lock function

- config/s2i/jenkins/master/configuration/init.groovy
- config/s2i/jenkins/master/configuration/scriptApproval.xml
Also made the script approvals more minimal (too minimal to even run out of the box) because having too many seems to break things
> Fix view s2i

- JenkinsfileTrigger
- config/Dockerfiles/cloud-image-compose/cloud-image-compose.sh
Little more use of git clone single-branch for some speedups
> Use more single branch cloning

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
This may help reduce the number of memory issues we see
> Add memsize to virt customize

- config/Dockerfiles/ostree-boot-image/ostree-boot-image.sh
- config/Dockerfiles/singlehost-test/Dockerfile
- config/Dockerfiles/singlehost-test/rpm-verify.yml
- config/Dockerfiles/singlehost-test/verify-rpm.sh
Need this stuff in the container to call from the Jenkinsfiles.
Moved it all out of ostree-boot image container so there is no need to add that container to the pod just for this. Will reduce the resource requirements for OpenShift
> Add expected vs running bits to container

- config/s2i/jenkins/master/configuration/jobs/fedora-stage-pipeline-merge/config.xml
> Add all pkgs stage merge job s2i

- config/Dockerfiles/singlehost-test/Dockerfile
> Add qemu-kvm to STR container

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
> Copy rpms to own dir

- config/Dockerfiles/singlehost-test/rpm-verify.yml
- config/Dockerfiles/singlehost-test/verify-rpm.sh
> More verbosity in nvr check

- config/Dockerfiles/rpmbuild/koji_build_pr.sh
- src/org/centos/pipeline/PipelineUtils.groovy
> Don't trigger on merged PRs and find nvr more often

- src/org/centos/pipeline/PipelineUtils.groovy
Reverts CentOS-PaaS-SIG/ci-pipeline#613
This broke the all packages pipeline. I will investigate why but I need to revert for now
> Revert "Replace JsonSlurper functions with read JSON"

- src/org/centos/pipeline/PipelineUtils.groovy
https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/613
> Replace json slurper with readJSON

- src/org/centos/pipeline/PipelineUtils.groovy
Reverts CentOS-PaaS-SIG/ci-pipeline#639
> Revert "Replace json slurper with readJSON"

- src/org/centos/pipeline/PipelineUtils.groovy
Gotten approval for this twice, just keep having to revert and catching bugs
> readJSON not slurper

- src/org/centos/pipeline/PipelineUtils.groovy
ugh
Reverts CentOS-PaaS-SIG/ci-pipeline#643
> Revert "readJSON not slurper"

- src/org/centos/pipeline/PipelineUtils.groovy
revert hell. The package was literally null so I thought this had broken things so I reverted
Reverts CentOS-PaaS-SIG/ci-pipeline#644
> Revert "Revert "readJSON not slurper""

- src/org/centos/pipeline/PipelineUtils.groovy
> Get rid of these .lck files

- src/org/centos/pipeline/PipelineUtils.groovy
The last thing to fix is jsonslurper handles something like comment: "Here is my comment\n" just fine, but readJSON does not
> readJSON can't parse newline

- src/org/centos/pipeline/PipelineUtils.groovy
* Changed PipelineUtils.obtainLock to execute mkdir -p before checking/creating lock
> Changed PipelineUtils.obtainLock to ensure that directory exists

- src/org/centos/pipeline/PipelineUtils.groovy
> Parse cli-build srpms

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
This PR should be reverted once rawhide latest boots again
> Hard code last known good rawhide image

- config/Dockerfiles/singlehost-test/package-test.sh
Could've sworn I already did this, but I guess not
> Save ansible-playbook output

- config/Dockerfiles/singlehost-test/verify-rpm.sh
This was my intention before and I totally forgot
> Save test_artifacts as well

- config/Dockerfiles/singlehost-test/verify-rpm.sh
This is related to https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/681
> Set pipefail before running rpm-verify.yml

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
I need to do a little more testing on this before merging
@thrix @bgoncalv 
> Pass a uuid to lock function

- config/Dockerfiles/singlehost-test/rpm-verify.yml
> Install python3-dnf when appropriate

- config/Dockerfiles/rpmbuild/koji_build_pr.sh
Make sure to test PR against HEAD of the branch.
> apply PR patches to head of branch

- config/Dockerfiles/singlehost-test/Dockerfile
As a workaround until STR works with 2.4 version.
> singlehost-test: install ansible 2.5

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
These methods assume you already called openshift.withcluster() and
openshift.withproject().  These should be used when doing parallel
jobs.
> Add ocVerifyPod and ocGetLogsFromPods

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
- config/Dockerfiles/rpmbuild/koji_build_pr.sh
- config/Dockerfiles/rpmbuild/pull_old_task.sh
retry to download files as sometimes there is network issues...
> retry to download files

- config/s2i/influxdb/influxdb-buildconfig-template.yaml
This adds automation of creating database and the admin user
> Influxdb update

- config/Dockerfiles/grafana/Dockerfile
- config/Dockerfiles/influxdb/Dockerfile
- config/s2i/grafana/grafana-buildconfig-template.yaml
- config/s2i/influxdb/influxdb-buildconfig-template.yaml
- allow anonymous ro access to Grafana
- update default version of Grafana and Indluxdb
> Metrics updates

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
The repo has lower priority, this should avoid errors trying to install packages that are not in official repos.
Also enable updates-testing repo if it is not in Rawhide.
> add repository with latest packages build in koji.

- src/org/centos/pipeline/PipelineUtils.groovy
sometimes there could be some temporary issue when sending message to provider, the pipeline should retry to send the message.
> retry to send topics in case of failure

- src/org/centos/pipeline/PipelineUtils.groovy
it looks like retry does not work if there is an exception, catch exception to see if problem is solved.
https://issues.jenkins-ci.org/browse/JENKINS-51454?jql=labels%20%3D%20declarative
> catch exception when sending message

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
> Adjust checkTests for container namespace

- src/org/centos/pipeline/PipelineUtils.groovy
Trying to fix issue like: https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/fedora-pr-pipeline-trigger/6376/console
> do not fail if checkTests in pipeline can't apply patch

- src/org/centos/pipeline/PipelineUtils.groovy
- vars/pipelineUtils.groovy
> Add function to get master node

- src/org/centos/pipeline/PipelineUtils.groovy
> Forgot [] in function

- Jenkinsfile
- config/s2i/jenkins/master/plugins.txt
> Update openshift plugin, move error reporting

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
- config/Dockerfiles/singlehost-test/package-test.sh
- src/org/centos/pipeline/PipelineUtils.groovy
For Fedora upstream pipeline to support PR on tests namespace these changes are required
Some trailing whitespaces got removed as well.
> Fedora upstream will support PRs on tests namespace

- config/Dockerfiles/singlehost-test/package-test.sh
Don't pass nvr variable when running STR playbook
> STR does not require nvr variable

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
attempt to solve issues like: https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/fedora-rawhide-build-pipeline/2165/artifact/package-tests/logs/FAIL_str_rust-cargo-test.log
> make sure fedora rawhide has GPG key imported

- Jenkinsfile
> Syntax fix

- config/s2i/jenkins/slave/Dockerfile
- src/org/centos/pipeline/PipelineUtils.groovy
- upstream-fedora-pipeline/AllPackagePipelineStageTrigger
If standard-test-roles is available use it to check for tag in the playbooks
> use ansible + str to check of tag on playbooks

- JenkinsfileTrigger
- config/s2i/jenkins/master/configuration/jobs/ci-pipeline-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedmsg-devel-receiver-test/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedmsg-devel-sender-test/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedora-build-pipeline-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedora-pr-added-pipeline-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/fedora-pr-new-pipeline-trigger/config.xml
- config/s2i/jenkins/master/plugins.txt
- src/org/centos/pipeline/PipelineUtils.groovy
Might need to add a commit for jms messaging version as I am waiting on a recently merged PR in a release
Had to remove topic from the messages as it prevents the messages from being sent on the bus
> Back to jms-1.1.2 format

- config/Dockerfiles/singlehost-test/Dockerfile
proper fix when STR with https://pagure.io/standard-test-roles/pull-request/303 is released
> workaround to improve gather_facts performance

- config/Dockerfiles/rpmbuild/koji_build_pr.sh
Fix for https://pagure.io/fedora-ci/general/issue/24
> merge PR to branch

- config/Dockerfiles/singlehost-test/package-test.sh
- config/Dockerfiles/str-container-test/container-test.sh
- src/org/centos/pipeline/PipelineUtils.groovy
it is related to https://pagure.io/fedora-ci/general/issue/24
> do not use patch from PR, use fetch -> merge

- src/org/centos/pipeline/PipelineUtils.groovy
if fails to parse ansible-playbook the function throws exception.
> fix how to check for tests

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
related to https://pagure.io/fedora-ci/general/issue/39
> disable GPG check for Rawhide

- src/org/centos/pipeline/PipelineUtils.groovy
Signed-off-by: Andrei Stepanov <astepano@redhat.com>
> Do not copy absent logs in executeInContainer()

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
The command returns NEVRA, but we just compare with name
> Add NAME queryformat

- src/org/centos/pipeline/PipelineUtils.groovy
@bgoncalv 
Makes the super unlucky timing situation even less likely
> Move cat of file in obtainLock function

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
> Don't query for whatprovides '' conflicts

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
Fix for https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline/issues/140
> virt-customize uses dnf to install packages

- utils/recycleOCBuilds
Reverts CentOS-PaaS-SIG/ci-pipeline#806
> Revert "Remove try from recycler"

- src/org/centos/pipeline/PipelineUtils.groovy
if for some reason the file existed, but could not be read, just retry...
> retry if can't read lock file

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
related to https://lists.fedoraproject.org/archives/list/ci@lists.fedoraproject.org/thread/4DAGSWFPZRFU5KXJVOTNFDVLU5W7H345/
> don't check gpg key on koji repos

- src/org/centos/pipeline/PipelineUtils.groovy
Signed-off-by: Andrei Stepanov <astepano@redhat.com>
> Add env var to turn off UMB send.

- config/Dockerfiles/cloud-image-compose/virt-customize.sh
related to https://pagure.io/fedora-ci/general/issue/20
> don't set priority for koji latest repo

- config/Dockerfiles/rpmbuild/koji_build_pr.sh
- config/Dockerfiles/rpmbuild/pull_old_task.sh
related to https://pagure.io/fedora-ci/general/issue/60
> allow download koji builds from stage env

- src/org/centos/pipeline/PipelineUtils.groovy
fix typo intruduced on https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/822/files
> fix typo on checkTests

- config/Dockerfiles/singlehost-test/Dockerfile
- config/Dockerfiles/singlehost-test/package-test.sh
there is an issue with synchronize module and python2, so make sure it runs with python3
> use ansible 2.8.0

- Jenkinsfile
> Display labels instead of 'Shell Script' in the Blue Ocean
